### ISSUE TITLE
SERVER : GET_PROFILE, 호출값, 반환값 정리 + follow

### ISSUE THREAD

**Issue by lay126** [lay126/fuding_wewe#21]

**Comment by lay126** [comment]
# 호출 URL

![image](https://cloud.githubusercontent.com/assets/4508613/9428408/8749d450-49e8-11e5-9c30-f4f65129ae0d.png)

**Comment by lay126** [comment]
# 요청 값

![image](https://cloud.githubusercontent.com/assets/4508613/9428409/96015734-49e8-11e5-8d5d-78edc59ddec6.png)

```
user_name = request.POST.get('user_name')
profile_name = request.POST.get('profile_name')
```

> > profile_name: 내가 누른 사람의 이름

**Comment by lay126** [comment]
# 반환 값 전체, 총 9개

![image](https://cloud.githubusercontent.com/assets/4508613/9428420/cc5768aa-49e8-11e5-9d46-26251954d67c.png)

**Comment by lay126** [comment]
# 내 프로필인지 판별 : me_flag

['me_flag'] = "yes"
['me_flag'] = "no"

# 팔로잉 중인지 판별 : follow_flag

dic['follow_flag'] = "no"
dic['follow_flag'] = "yes"

**Comment by YeoeunJeong** [comment]
user_followers   나를 팔로잉 한 사람 수
user_followings  내가 팔로잉 한 사람 수
